Create history screen (no backend connection yet)
holtzmak/Humane-Transport pull request #144
Opened 2021-02-01 22:03 UTC by holtzmak

Half of #131 , will need the back end connection yet.

I've added a preview object for ATRs - we'll be able to reuse this I think with in-progress ATRs if we allow null fields and the be safe with them (for example, maybe we always require a receiver and date so as not to interrupt previews). The `ATWPreViewModel` can also be reused for in-progress items, we'll just filter which items are in the model: in-progress or historical.

The hookup between the view model and the screen using it is so small that it doesn't make sense for us to combine new_travel and history. They can be similar with different buttons for now. Thank you `ListView.builder()`.

I imagine that record selection might be funny with the provider pattern, we specify the `onTap()` for each card to open another widget before we build the widget that holds all the cards (but since business code drives GUI I suppose not a problem).

I also added some test tools in the commit. Our big form is cumbersome to write (easier now with the tools), but I'm struggling with a nicer way to do it: if we split it up more it is hard to change, and if we make one mega-object it becomes anti-pattern to object-oriented code style.

2021-02-01 22:05 UTC, holtzmak commented on app/lib/core/models/contingency_plan_info.dart
> +      {@required DateTime eventDateAndTime,
Combined date and time for many objects, missed it before.

2021-02-01 22:06 UTC, holtzmak commented on app/lib/ui/widgets/atr_preview.dart
> +              'Date: ${DateFormat("yyyy-MM-dd hh:mm").format(atr.vehicleInfo.dateAndTimeLoaded)}, Animals: ${atr.vehicleInfo.animalSpeciesLoaded().join(',')}'),
- [ ] Now that I look at it... we can just drop `Date: , Animals` because it is obvious from output.

2021-02-01 22:08 UTC, holtzmak commented on app/test/ui/widgets/atr_preview_test.dart
> +      await tester.pumpWidget(new MaterialApp(
Related to [this discussion](https://github.com/flutter/flutter/issues/11859). It's not very obvious, and it doesn't look like they're gonna make it more obvious either.

2021-02-01 22:08 UTC, holtzmak commented on app/test/ui/widgets/atr_preview_test.dart
> +      expect(find.text("Date: ${testDate.toString()}, Animals: $testSpecies"),
- [ ] Oops I broke this test with changing the formatter, will drop Date: and Animals: at the same time

2021-02-02 03:58 UTC, holtzmak commented on app/test/ui/widgets/atr_preview_test.dart
> +              "${DateFormat("yyyy-MM-dd hh:mm").format(testDate)} $testSpecies"),
Usually you don't use production code in the test, but this is a dumb test for a dumb widget.

2021-02-02 04:23 UTC, MummenRider requested changes
I know this commit is specifically for History Screen, but since you have a PR open already, 

- [ ] please refactor the models as shown below. As you can see, less code here.
```
@immutable
class AcknowledgementInfo {
  final File shipperAck;
  final File transporterAck;
  final File receiverAck;

  AcknowledgementInfo({
    @required this.shipperAck,
    @required this.transporterAck,
    @required this.receiverAck,
  });
```
- [ ] I think you refactor the add method in ATRViewModel and make it as Future<void>. Posting should be asynchronous method. We should await if record can be posted or not.

2021-02-02 18:57 UTC, holtzmak commented
As per above comment, I will add a placeholder for the database serializer/deserializer/interface service so as to make it obvious that the `add` function is not a `save` function.

2021-02-02 19:03 UTC, holtzmak commented
@MummenRider additionally, we will have to keep the initializer list for some fields because of the nature of lists (any fields with `_field` cannot be accessed by `this._field` in the constructor. I should be able to update the other fields.

2021-02-02 19:23 UTC, holtzmak commented on app/test/ui/widgets/atr_preview_test.dart
> +      final testRecWithDelvInfo = testAnimalTransportRecord().withDeliveryInfo(
Note: We unfortunately cannot use Dart's fantastic cascade operator with the `with()` functions because they return an object.

2021-02-02 19:25 UTC, holtzmak commented on app/test/ui/widgets/atr_preview_test.dart
> +      final testRecWithDelvInfo = testAnimalTransportRecord().withDeliveryInfo(
Also refactored test for easier reading (this is why I made the `with()` functions, better use them >:( )

2021-02-02 22:33 UTC, MummenRider approved these changes
LGTM!

2021-02-02 23:26 UTC, merged